config/routes.rb
Rails.application.routes.draw do
  resources :sensor_errors
  resources :smoke_levels
  resources :ambient_light_levels
  resources :heat_indices
  resources :humidities
  resources :temperatures

end

app/models/temperature.rb
class Temperature
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/controllers/temperatures_controller.rb
include TimestampParamsHelper

class TemperaturesController < ApplicationController
  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  # GET /temperatures
  # GET /temperatures.json
  def index
    @temperatures = Temperature.all
  end

  # GET /temperatures/1
  # GET /temperatures/1.json
  def show
  end

  # GET /temperatures/new
  def new
    @temperature = Temperature.new
  end

  # GET /temperatures/1/edit
  def edit
  end

  # POST /temperatures
  # POST /temperatures.json
  def create
    @temperature = Temperature.new(packTimestampParams(temperature_params))

    respond_to do |format|
      if @temperature.save
        format.html { redirect_to @temperature, notice: 'Temperature was successfully created.' }
        format.json { render :show, status: :created, location: @temperature }
      else
        format.html { render :new }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperatures/1
  # PATCH/PUT /temperatures/1.json
  def update
    respond_to do |format|
      if @temperature.update(packTimestampParams(temperature_params))
        format.html { redirect_to @temperature, notice: 'Temperature was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperatures/1
  # DELETE /temperatures/1.json
  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url, notice: 'Temperature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperature
      @temperature = Temperature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperature_params
      params.require(:temperature).permit(:sensorID, :value, :measuredAt)
    end
end

app/helpers/temperature_helper.rb
module TemperatureHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/views/temperature/_form.html.erb
<%= form_for(@temperature) do |f| %>
  <% if @temperature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

      <ul>
      <% @temperature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temperature/edit.html.erb
<h1>Editing Temperature</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperature %> |
<%= link_to 'Back', temperatures_path %>

app/views/temperature/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temperatures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperatures.each do |temperature| %>
      <tr>
        <td><%= link_to 'Show', temperature %></td>
        <td><%= link_to 'Edit', edit_temperature_path(temperature) %></td>
        <td><%= link_to 'Destroy', temperature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperature', new_temperature_path %>

app/views/temperature/new.html.erb
<h1>New Temperature</h1>

<%= render 'form' %>

<%= link_to 'Back', temperatures_path %>

app/views/temperature/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_temperature_path(@temperature) %> |
<%= link_to 'Back', temperatures_path %>