config/routes.rb
Rails.application.routes.draw do
  resources :sensor_errors
  resources :smoke_levels
  resources :ambient_light_levels
  resources :heat_indices
  resources :humidities
  resources :temperatures

end

app/models/smoke_level.rb
class SmokeLevel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/controllers/smoke_levels_controller.rb
include TimestampParamsHelper

class SmokeLevelsController < ApplicationController
  before_action :set_smoke_level, only: [:show, :edit, :update, :destroy]

  # GET /smoke_levels
  # GET /smoke_levels.json
  def index
    @smoke_levels = SmokeLevel.all
  end

  # GET /smoke_levels/1
  # GET /smoke_levels/1.json
  def show
  end

  # GET /smoke_levels/new
  def new
    @smoke_level = SmokeLevel.new
  end

  # GET /smoke_levels/1/edit
  def edit
  end

  # POST /smoke_levels
  # POST /smoke_levels.json
  def create
    @smoke_level = SmokeLevel.new(packTimestampParams(moke_level_params))

    respond_to do |format|
      if @smoke_level.save
        format.html { redirect_to @smoke_level, notice: 'Smoke level was successfully created.' }
        format.json { render :show, status: :created, location: @smoke_level }
      else
        format.html { render :new }
        format.json { render json: @smoke_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smoke_levels/1
  # PATCH/PUT /smoke_levels/1.json
  def update
    respond_to do |format|
      if @smoke_level.update(packTimestampParams(moke_level_params))
        format.html { redirect_to @smoke_level, notice: 'Smoke level was successfully updated.' }
        format.json { render :show, status: :ok, location: @smoke_level }
      else
        format.html { render :edit }
        format.json { render json: @smoke_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smoke_levels/1
  # DELETE /smoke_levels/1.json
  def destroy
    @smoke_level.destroy
    respond_to do |format|
      format.html { redirect_to smoke_levels_url, notice: 'Smoke level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smoke_level
      @smoke_level = SmokeLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smoke_level_params
      params.require(:smoke_level).permit(:sensorID, :value, :measuredAt)
    end
end

app/helpers/smoke_level_helper.rb
module SmokeLevelHelper
end

app/helpers/smoke_levels_helper.rb
module SmokeLevelsHelper
end

app/views/smoke_levels/_form.html.erb
<%= form_for(@smoke_level) do |f| %>
  <% if @smoke_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smoke_level.errors.count, "error") %> prohibited this smoke_level from being saved:</h2>

      <ul>
      <% @smoke_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sensorID %><br>
    <%= f.text_field :sensorID %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :measuredAt %><br>
    <%= f.datetime_select :measuredAt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smoke_levels/edit.html.erb
<h1>Editing Smoke Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @smoke_level %> |
<%= link_to 'Back', smoke_levels_path %>

app/views/smoke_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Smoke Levels</h1>

<table>
  <thead>
    <tr>
      <th>Sensor ID</th>
      <th>Value</th>
      <th>Measured At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @smoke_levels.each do |smoke_level| %>
      <tr>
        <td><%= smoke_level.sensorID %></td>
        <td><%= smoke_level.value %></td>
        <td><%= smoke_level.measuredAt %></td>
        <td><%= link_to 'Show', smoke_level %></td>
        <td><%= link_to 'Edit', edit_smoke_level_path(smoke_level) %></td>
        <td><%= link_to 'Destroy', smoke_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smoke level', new_smoke_level_path %>

app/views/smoke_levels/new.html.erb
<h1>New Smoke Level</h1>

<%= render 'form' %>

<%= link_to 'Back', smoke_levels_path %>

app/views/smoke_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensorid:</strong>
  <%= @smoke_level.sensorID %>
</p>

<p>
  <strong>Value:</strong>
  <%= @smoke_level.value %>
</p>

<p>
  <strong>Measuredat:</strong>
  <%= @smoke_level.measuredAt %>
</p>

<%= link_to 'Edit', edit_smoke_level_path(@smoke_level) %> |
<%= link_to 'Back', smoke_levels_path %>