config/routes.rb
Rails.application.routes.draw do
  resources :sensor_errors
  resources :smoke_levels
  resources :ambient_light_levels
  resources :heat_indices
  resources :humidities
  resources :temperatures

end

app/models/ambient_light_level.rb
class AmbientLightLevel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/models/heat_index.rb
class HeatIndex
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/models/humidity.rb
class Humidity
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/models/sensor_error.rb
class SensorError
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: String
  field :occurredAt, type: DateTime
end

app/models/smoke_level.rb
class SmokeLevel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/models/temperature.rb
class Temperature
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/controllers/ambient_light_levels_controller.rb
include TimestampParamsHelper

class AmbientLightLevelsController < ApplicationController
  before_action :set_ambient_light_level, only: [:show, :edit, :update, :destroy]

  # GET /ambient_light_levels
  # GET /ambient_light_levels.json
  def index
    @ambient_light_levels = AmbientLightLevel.all
  end

  # GET /ambient_light_levels/1
  # GET /ambient_light_levels/1.json
  def show
  end

  # GET /ambient_light_levels/new
  def new
    @ambient_light_level = AmbientLightLevel.new
  end

  # GET /ambient_light_levels/1/edit
  def edit
  end

  # POST /ambient_light_levels
  # POST /ambient_light_levels.json
  def create
    @ambient_light_level = AmbientLightLevel.new(packTimestampParams(ambient_light_level_params))

    respond_to do |format|
      if @ambient_light_level.save
        format.html { redirect_to @ambient_light_level, notice: 'Ambient light level was successfully created.' }
        format.json { render :show, status: :created, location: @ambient_light_level }
      else
        format.html { render :new }
        format.json { render json: @ambient_light_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambient_light_levels/1
  # PATCH/PUT /ambient_light_levels/1.json
  def update
    respond_to do |format|
      if @ambient_light_level.update(packTimestampParams(ambient_light_level_params))
        format.html { redirect_to @ambient_light_level, notice: 'Ambient light level was successfully updated.' }
        format.json { render :show, status: :ok, location: @ambient_light_level }
      else
        format.html { render :edit }
        format.json { render json: @ambient_light_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambient_light_levels/1
  # DELETE /ambient_light_levels/1.json
  def destroy
    @ambient_light_level.destroy
    respond_to do |format|
      format.html { redirect_to ambient_light_levels_url, notice: 'Ambient light level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambient_light_level
      @ambient_light_level = AmbientLightLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambient_light_level_params
      params.require(:ambient_light_level).permit(:sensorID, :value, :measuredAt)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/humidities_controller.rb
include TimestampParamsHelper

class HumiditiesController < ApplicationController
  before_action :set_humidity, only: [:show, :edit, :update, :destroy]

  # GET /humidities
  # GET /humidities.json
  def index
    @humidities = Humidity.all
  end

  # GET /humidities/1
  # GET /humidities/1.json
  def show
  end

  # GET /humidities/new
  def new
    @humidity = Humidity.new
  end

  # GET /humidities/1/edit
  def edit
  end

  # POST /humidities
  # POST /humidities.json
  def create
    @humidity = Humidity.new(packTimestampParams(humidity_params))

    respond_to do |format|
      if @humidity.save
        format.html { redirect_to @humidity, notice: 'Humidity was successfully created.' }
        format.json { render :show, status: :created, location: @humidity }
      else
        format.html { render :new }
        format.json { render json: @humidity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humidities/1
  # PATCH/PUT /humidities/1.json
  def update
    respond_to do |format|
      if @humidity.update(packTimestampParams(humidity_params))
        format.html { redirect_to @humidity, notice: 'Humidity was successfully updated.' }
        format.json { render :show, status: :ok, location: @humidity }
      else
        format.html { render :edit }
        format.json { render json: @humidity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humidities/1
  # DELETE /humidities/1.json
  def destroy
    @humidity.destroy
    respond_to do |format|
      format.html { redirect_to humidities_url, notice: 'Humidity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_humidity
      @humidity = Humidity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def humidity_params
      params.require(:humidity).permit(:sensorID, :value, :measuredAt)
    end
end

app/helpers/ambient_light_level_helper.rb
module AmbientLightLevelHelper
end

app/helpers/ambient_light_levels_helper.rb
module AmbientLightLevelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heat_index_helper.rb
module HeatIndexHelper
end

app/helpers/heat_indices_helper.rb
module HeatIndicesHelper
end

app/helpers/humidities_helper.rb
module HumiditiesHelper
end

app/helpers/humidity_helper.rb
module HumidityHelper
end

app/helpers/sensor_error_helper.rb
module SensorErrorHelper
end

app/helpers/sensor_errors_helper.rb
module SensorErrorsHelper
end

app/helpers/sensor_reading_helper.rb
module SensorReadingHelper
end

app/helpers/smoke_level_helper.rb
module SmokeLevelHelper
end

app/helpers/smoke_levels_helper.rb
module SmokeLevelsHelper
end

app/helpers/temperature_helper.rb
module TemperatureHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/helpers/timestamp_params_helper.rb
module TimestampParamsHelper

  def packTimestampParams(timestamp_params)
    year = timestamp_params["measuredAt(1i)"].to_i
    month = timestamp_params["measuredAt(2i)"].to_i
    day = timestamp_params["measuredAt(3i)"].to_i
    hour = timestamp_params["measuredAt(4i)"].to_i
    minute = timestamp_params["measuredAt(5i)"].to_i

    dateTimeFromParams = DateTime.new(year, month, day, hour, minute)
    excludedParams = ["measuredAt(1i)","measuredAt(2i)","measuredAt(3i)","measuredAt(4i)","measuredAt(5i)"]

    theParams = timestamp_params.except(*excludedParams)
    theParams[:measuredAt] = dateTimeFromParams
    return theParams
  end
end

app/views/ambient_light_levels/_form.html.erb
<%= form_for(@ambient_light_level) do |f| %>
  <% if @ambient_light_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ambient_light_level.errors.count, "error") %> prohibited this ambient_light_level from being saved:</h2>

      <ul>
      <% @ambient_light_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sensorID %><br>
    <%= f.text_field :sensorID %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :measuredAt %><br>
    <%= f.datetime_select :measuredAt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambient_light_levels/edit.html.erb
<h1>Editing Ambient Light Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @ambient_light_level %> |
<%= link_to 'Back', ambient_light_levels_path %>

app/views/ambient_light_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ambient Light Levels</h1>

<table>
  <thead>
    <tr>
      <th>Sensor ID</th>
      <th>Value</th>
      <th>Measured At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ambient_light_levels.each do |ambient_light_level| %>
      <tr>
        <td><%= ambient_light_level.sensorID %></td>
        <td><%= ambient_light_level.value %></td>
        <td><%= ambient_light_level.measuredAt %></td>
        <td><%= link_to 'Show', ambient_light_level %></td>
        <td><%= link_to 'Edit', edit_ambient_light_level_path(ambient_light_level) %></td>
        <td><%= link_to 'Destroy', ambient_light_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambient light level', new_ambient_light_level_path %>

app/views/ambient_light_levels/new.html.erb
<h1>New Ambient Light Level</h1>

<%= render 'form' %>

<%= link_to 'Back', ambient_light_levels_path %>

app/views/ambient_light_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensorid:</strong>
  <%= @ambient_light_level.sensorID %>
</p>

<p>
  <strong>Value:</strong>
  <%= @ambient_light_level.value %>
</p>

<p>
  <strong>Measuredat:</strong>
  <%= @ambient_light_level.measuredAt %>
</p>

<%= link_to 'Edit', edit_ambient_light_level_path(@ambient_light_level) %> |
<%= link_to 'Back', ambient_light_levels_path %>