config/routes.rb
Rails.application.routes.draw do
  resources :sensor_errors
  resources :smoke_levels
  resources :ambient_light_levels
  resources :heat_indices
  resources :humidities
  resources :temperatures

end

app/models/humidity.rb
class Humidity
  include Mongoid::Document
  include Mongoid::Timestamps

  field :sensorID, type: String
  field :value, type: Float
  field :measuredAt, type: DateTime
end

app/controllers/humidities_controller.rb
include TimestampParamsHelper

class HumiditiesController < ApplicationController
  before_action :set_humidity, only: [:show, :edit, :update, :destroy]

  # GET /humidities
  # GET /humidities.json
  def index
    @humidities = Humidity.all
  end

  # GET /humidities/1
  # GET /humidities/1.json
  def show
  end

  # GET /humidities/new
  def new
    @humidity = Humidity.new
  end

  # GET /humidities/1/edit
  def edit
  end

  # POST /humidities
  # POST /humidities.json
  def create
    @humidity = Humidity.new(packTimestampParams(humidity_params))

    respond_to do |format|
      if @humidity.save
        format.html { redirect_to @humidity, notice: 'Humidity was successfully created.' }
        format.json { render :show, status: :created, location: @humidity }
      else
        format.html { render :new }
        format.json { render json: @humidity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humidities/1
  # PATCH/PUT /humidities/1.json
  def update
    respond_to do |format|
      if @humidity.update(packTimestampParams(humidity_params))
        format.html { redirect_to @humidity, notice: 'Humidity was successfully updated.' }
        format.json { render :show, status: :ok, location: @humidity }
      else
        format.html { render :edit }
        format.json { render json: @humidity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humidities/1
  # DELETE /humidities/1.json
  def destroy
    @humidity.destroy
    respond_to do |format|
      format.html { redirect_to humidities_url, notice: 'Humidity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_humidity
      @humidity = Humidity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def humidity_params
      params.require(:humidity).permit(:sensorID, :value, :measuredAt)
    end
end

app/helpers/humidities_helper.rb
module HumiditiesHelper
end

app/helpers/humidity_helper.rb
module HumidityHelper
end

app/views/humidities/_form.html.erb
<%= form_for(@humidity) do |f| %>
  <% if @humidity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@humidity.errors.count, "error") %> prohibited this humidity from being saved:</h2>

      <ul>
      <% @humidity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sensorID %><br>
    <%= f.text_field :sensorID %>
  </div>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :measuredAt %><br>
    <%= f.datetime_select :measuredAt %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/humidities/edit.html.erb
<h1>Editing Humidity</h1>

<%= render 'form' %>

<%= link_to 'Show', @humidity %> |
<%= link_to 'Back', humidities_path %>

app/views/humidities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Humidities</h1>

<table>
  <thead>
    <tr>
      <th>Sensor ID</th>
      <th>Value</th>
      <th>Measured At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humidities.each do |humidity| %>
      <tr>
        <td><%= humidity.sensorID %></td>
        <td><%= humidity.value %></td>
        <td><%= humidity.measuredAt %></td>
        <td><%= link_to 'Show', humidity %></td>
        <td><%= link_to 'Edit', edit_humidity_path(humidity) %></td>
        <td><%= link_to 'Destroy', humidity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Humidity', new_humidity_path %>

app/views/humidities/new.html.erb
<h1>New Humidity</h1>

<%= render 'form' %>

<%= link_to 'Back', humidities_path %>

app/views/humidities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensorid:</strong>
  <%= @humidity.sensorID %>
</p>

<p>
  <strong>Value:</strong>
  <%= @humidity.value %>
</p>

<p>
  <strong>Measuredat:</strong>
  <%= @humidity.measuredAt %>
</p>

<%= link_to 'Edit', edit_humidity_path(@humidity) %> |
<%= link_to 'Back', humidities_path %>